
language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - nosetests --with-coverage
addons:
    code_climate:
        repo_token: 5227ab0975979d05177388e52d802758bf982286e4abc9a1992cb37c3f099ab8
